# Makefile for vector class test
#
# Made for your convenience. Also used by GitHub Actions.
# Code By: Michael Wrona
# Creatd: 14 Sept 2021

CC=g++
CFLAGS=-Wall -std=c++11
OUTNAME=vectortest.out

all:
	$(CC) -o $(OUTNAME) main.cpp ../vectorf.cpp -I../ $(CFLAGS)

clean:
	rm $(OUTNAME)
