# Makefile for vector class test
# Code By: Michael Wrona
# Creatd: 14 Sept 2021

CC=g++
CFLAGS=-Wall -std=c++11
OUTNAME=maintest

all:
	$(CC) -o $(OUTNAME) main.cpp ../vectorf.cpp -I../ $(CFLAGS)
	./$(OUTNAME)

clean:
	rm $(OUTNAME)
