name: Test Compile Example Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile-and-run:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile and run code
        run: |
          cd examples/
          make
          ./vectortest.out
